dist: trusty
language: node_js
node_js:
  - "8.11.2"
script: "npm run build"
cache: "npm"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/ # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
