language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
notifications:
  email: false
script:
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/ # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
